name: cherry
description: Simple yet powerful, open-source SpaceX launch tracker.

version: 2.10.1+68

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  add_2_calendar: ^1.4.0
  big_tip: ^1.1.1
  cherry_components: ^0.0.1+3
  dio: ^3.0.10
  expand_widget: ^1.0.0+1
  equatable: ^1.2.5
  flutter_email_sender: ^3.0.1
  flutter_i18n: ^0.19.2
  flutter_local_notifications: ^1.4.4+4
  flutter_map: ^0.10.1+1
  flutter_markdown: ^0.4.4
  flutter_swiper: ^1.1.6
  flutter_web_browser: ^0.12.0
  google_fonts: ^1.1.0
  intl: ^0.16.1
  launch_review: ^2.0.0
  lint: ^1.2.0
  package_info: ^0.4.3
  provider: ^4.3.2+2
  quick_actions: ^0.4.0+8
  row_collection: ^0.2.4
  search_page: ^1.3.0
  share: ^0.6.5
  shared_preferences: ^0.5.10
  sliver_fab: ^1.0.0
  system_setting: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter_icons:
  image_path: assets/icons/icon_app.png
  android: false
  ios: true

flutter_native_splash:
  image: assets/icons/icon_splash.png
  color: "#151515"

flutter:
  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true
