name: cherry
description: Simple yet powerful, open-source SpaceX launch tracker.

version: 2.12.0+73

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  add_2_calendar: ^1.4.0
  big_tip: ^1.1.1+1
  cherry_components: ^0.0.1+5
  dio: ^3.0.10
  expand_widget: ^1.1.0+1
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0
  flutter_i18n:
  flutter_local_notifications: ^3.0.3
  flutter_map: ^0.10.1+1
  flutter_markdown: ^0.5.2
  flutter_swiper: ^1.1.6
  flutter_web_browser: ^0.13.1
  google_fonts: ^1.1.1
  in_app_review: ^1.0.4
  lint: 1.4.0-dev.d210.1
  package_info: ^0.4.3+2
  provider: ^4.3.3
  quick_actions: ^0.4.0+10
  row_collection: ^0.2.4
  search_page: ^1.4.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  sliver_fab: ^1.0.0
  system_setting: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.2.5
  mockito: ^4.1.3

flutter_icons:
  image_path: assets/icons/icon_app.png
  android: false
  ios: true

flutter_native_splash:
  image: assets/icons/icon_splash.png
  color: "#151515"

flutter:
  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true
